### PR TITLE
PYTHON-649

### PR DESCRIPTION
**Pull request by mambocab**
I don't necessarily expect this to get merged as-is; this is more of a review request. I want to check:

- that others like the `for user_type, conn in product(set(udts), connection._connections.values())` approach
- that the tests in `tests/integration/cqlengine/model/test_udts.py` cover the cases we care about, in terms of ordering UDT definitions and connection creations. I think they have, but I'd like a review and to have another look myself.

### CODE REVIEW

File: cassandra/cqlengine/models.py [hunk 1]
```diff
@@ -1021,8 +1022,8 @@ def _transform_column(col_name, col_obj):
         for col in column_dict.values():
             columns.resolve_udts(col, udts)
 
-        for user_type in set(udts):
-            user_type.register_for_keyspace(klass._get_keyspace())
+        for user_type, conn in product(set(udts), connection._connections.values()):
+            user_type.register_for_keyspace(klass._get_keyspace(), connection=conn)
```
Comment (aboudreault) [inline cassandra/cqlengine/models.py]: This would probably work. However, It might be better to keep the 'connection' logic **only** in the management commands. I think It  will become confusing if we start adding some of that logic in different places. What do you think?

Comment (mambocab) [inline cassandra/cqlengine/models.py]: I see what you mean -- let me have a look at what consolidating the logic would involve.

**Comment by mambocab** [comment]
Pushed 5c649a9; rebasing for a cleaner history.

**Comment by mambocab** [comment]
I've pushed a [new test for behavior that was broken with #656](692c3a8), and [a fix for that](c4f9989). I think there's definitely some code dedupe to be done here before merge.

File: cassandra/cqlengine/connection.py [hunk 2]
```diff
@@ -222,7 +228,14 @@ def set_session(s):
...
 
-    conn = get_connection()
+    try:
+        conn = get_connection()
+    except CQLEngineException:
+        # no default connection set; initalize one
+        default_name = 'default'
+        conn = Connection.from_session(default_name, s)
+        _connections[default_name] = conn
+        set_default_connection[default_name]
```
Comment (aboudreault) [inline cassandra/cqlengine/connection.py]: This doesn't seem to work as expected. I'm getting this exception:
```
    connection.set_session(s)
  File "/home/aboudreault/dev/python-driver/cassandra/cqlengine/connection.py", line 238, in set_session
    set_default_connection[default_name]
TypeError: 'function' object has no attribute '__getitem__'
```
You probably want to do set_default_connection(...).

**Comment by mambocab** [comment]
Fixed the `set_default_connection` call; not sure how I missed that.

Unit tests now pass locally. Do you agree that it's worth the time to refactor before we commit? I don't like the duplication between `register_connection` and `set_session` -- it's only a couple lines, but I think they're likely to change relatively soon.

**Comment by aboudreault** [comment]
+1 

I agree that set_session could be removed in the next major release. register_connection should be able to register a new connection from a session object. I don't have any objection if we can add that support now but we need to keep set_session. You can add  a note about the the removal of it in https://datastax-oss.atlassian.net/browse/PYTHON-504

**Comment by aboudreault** [comment]
Looks good. it might be good to add some documentation about that, with 2 examples, and also specifying what configuration arguments are incompatible with the session param.

**Comment by aboudreault** [comment]
+1
